# Generated by Django 6.0.1 on 2026-08-29 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_book', models.FileField(upload_to='subject_books/')),
                ('book_extracted_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_fname', models.CharField(max_length=100)),
                ('student_lname', models.CharField(max_length=100)),
                ('student_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('answer_sheet', models.FileField(upload_to='student_answers/')),
                ('tutor_solution_text', models.TextField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('confidence', models.CharField(default='Medium', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('rubric_data', models.JSONField(blank=True, default=dict)),
                ('book_citations', models.TextField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.submission')),
            ],
        ),
    ]
